version: "3"

services:
    db:
        build:
            context: /postgresdb
            dockerfile: db.Dockerfile
        volumes:
            - ./var/pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432